config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archives/index'
  resources :entries
  root to: 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true

  belongs_to :category

  def day
    self.created_at.strftime("%b %-e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.where('created_at >= ?', Date.today)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">
                Entries for <%= day %>
            </h3>
            <nav class="level is-mobile">
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Calories</p>
                        <p class="title"><%= entries.pluck(:calories).sum %>g</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Protein</p>
                        <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Carbohydrates</p>
                        <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Fats</p>
                        <p class="title"><%= entries.pluck(:fats).sum %>g</p>
                    </div>
                </div>
            </nav>
            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                    <div class="card">
                        <div class="card-content">
                            <strong><%= entry.meal_type %></strong><br/>
                            <%= entry.calories %> calories,
                            <%= entry.proteins %>g protein,
                            <%= entry.carbohydrates %>g carbs,
                            <%= entry.fats %>g fats
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Category</h1>

    <%= render 'form', category: @category %>
  </div>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New Category</h1>

    <%= render 'form', category: @category %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @category.title %>
      </p>

      <div class="panel-block">
        Category title: <%= @category.title %>
      </div>
    </nav>

    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Edit', edit_category_path(@category), class: 'button is-gray' %>
        <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-gray' %>
      </div>
      <div class="column">

      </div>
    </div>

  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: 'label' %>
    <%= form.text_field :meal_type, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :category, class: 'label' %>
    <div class="select">
      <%= form.select :category_id, Category.all.collect { |c| [c.title, c.id] }, {} %>
    </div>
  </div>

  <div class="field">
    <%= form.label :calories, class: 'label' %>
    <%= form.number_field :calories, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: 'label' %>
    <%= form.number_field :proteins, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: 'label' %>
    <%= form.number_field :carbohydrates, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :fats, class: 'label' %>
    <%= form.number_field :fats, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Entry</h1>

        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<h1 class="title is-spaced mt-5 has-text-centered">Entries</h1>

<div class="columns mt-6 is-centered is-multiline">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %>: <%= entry.category.title if entry.category %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: 'card-footer-item' %>
          <%= link_to 'Edit', edit_entry_path(entry), class: 'card-footer-item' %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to 'View all entries', archives_index_path, class: 'button is-link is-outlined is-centered' %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-one-third">
        <h1 class="is-size-2 has-text-weight-bold mb-3">New Entry</h1>

        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= @entry.created_at.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading">
        <%= @entry.meal_type %>:
        <%= @entry.category&.title %>
      </p>
     
      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins: <%= @entry.proteins %>
      </div>

      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>
      </div>
    </nav> 

    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Edit', edit_entry_path(@entry), class: 'button is-gray' %> |
        <%= link_to 'Delete', entry_path(@entry), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-gray' %>
      </div>
      <div class="column">
        
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <% if notice.present? %>
      <div class="notification is-primary is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: 'navbar-item' do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" height="20" width="20" fill="#fff">
              <g>
                <path d="m7.905233,1.487743c-0.397441,0 -0.719676,0.476297 -0.719676,1.064945l0,5.324725l-0.719676,0l0,-5.324725c0,-0.588648 -0.322235,-1.064945 -0.719676,-1.064945s-0.719676,0.476297 -0.719676,1.064945l0,5.324725l-0.719676,0l0,-5.324725c0,-0.588648 -0.322235,-1.064945 -0.719676,-1.064945s-0.719676,0.476297 -0.719676,1.064945l0,6.38967c0,0.588648 0.322235,1.064945 0.719676,1.064945l1.439351,0l0,7.454615c0,0.588648 0.322235,1.064945 0.719676,1.064945s0.719676,-0.476297 0.719676,-1.064945l0,-7.454615l1.439351,0c0.397441,0 0.719676,-0.476297 0.719676,-1.064945l0,-6.38967c0,-0.588648 -0.322235,-1.064945 -0.719676,-1.064945z" />
                <path d="m13.727674,1.744861c-1.303527,0 -2.360348,1.414886 -2.360348,3.161095c0,1.374747 0.658857,2.532366 1.573565,2.967643l0,9.676738c0,0.582432 0.352257,1.053698 0.786783,1.053698c0.434501,0 0.786783,-0.471267 0.786783,-1.053698l0,-9.676738c0.914684,-0.435276 1.573565,-1.592896 1.573565,-2.967643c0,-1.746209 -1.056846,-3.161095 -2.360348,-3.161095z" />
              </g>
            </svg>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <% end %>
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to 'Create new entry', new_entry_path, class: 'button is-success' %>
            </span>
            <span class="navbar-item">
              <%= link_to 'Create new category', new_category_path, class: 'button is-info' %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Foodlog
        <% end %>
      </h1>
    </div>
  </div>
</section>